######################################################################
# Automatically generated by qmake (2.01a) vr feb. 10 05:11:30 2012
######################################################################

TEMPLATE = app
CONFIG -= app_bundle

DEPENDPATH += .
INCLUDEPATH += . ..
LIBS += -ldazeus-qt -ldazeus
MOC_DIR = build
OBJECTS_DIR = build
QT -= gui

# Input
SOURCES += karmaplugin.cpp

HEADERS += karmaplugin.h
